:arrow_down: Downgrade pyinstaller
Pyinstaller 5.1 on Python 3.10.4 is apparently broken
ValueError: Package 'soundfile' does not exist or is not a package!